### ISSUE TITLE
Don't stop the cursor on the first line of selection when I use `vii`

### ISSUE THREAD

**Issue by skywind3000** [michaeljsmith/vim-indent-object#15]
Great plugin, I love it because it is much more lightweight that textobj-user stuffs.

Some people prefer to use viw, vip, vii before any action (delete / change) then they take some actions when they confirm the selection is what they want. 

It is safer to select a text-object before taking any action, especially for big text objects containing many characters. So, I always use `vii` with this plugin. 

But I noticed that after select text with `vii` the cursor stopped on the first line of the selection not the last line, for example:

```text
          this is line 1
<cursor>  this is line 2
          this is line 3
```

The cursor is on line 2, when I type `vii` the three lines are selected, and the cursor should located on the last line, but it rewind to the first line. It is different from other text object selecting behavior. 

When I use `viw` to select a word, the cursor stops on the last character of the selection, while `vip` will move the cursor to the last line of the selection.

I suppose vim-indent-object's selection behavior should correspond to other existing text-object's. Stopping  cursor on the last line or last character of the selection is important because when I am editing I usually continue moving cursor down, if I made a wrong selection and cancel it by `ESC`, the cursor is usually close to the origin position before selection.

Is it possible to make an update for this ? If so I don't need press an `o` command after `vii`.

**Comment by skywind3000** [comment]
I have made an PR for this: 
https://github.com/michaeljsmith/vim-indent-object/pull/16

Will you please review it ??

**Comment by michaeljsmith** [comment]
Merged - thanks for the contribution :)
