### ISSUE TITLE
Adding a FOSS license

### ISSUE THREAD

**Issue by ColinKennedy** [michaeljsmith/vim-indent-object#30]
Hi, I love and use this plug-in every day. It makes working with code in Vim so much better! My workplace is cautious about allowing code without a `LICENSE` file and it'd be a big help if this plug-in could use a FOSS license. I'm sure others in the same position and would appreciate it too. Could a FOSS license please be added if this plug-in is meant for public use?

**Comment by michaeljsmith** [comment]
Hi Colin,

Yes fair enough, added an MIT license, hopefully that helps.

**Comment by ColinKennedy** [comment]
That's perfect, thank you!

**Comment by EtiamNullam** [comment]
I believe this issue can be closed.

**Comment by ColinKennedy** [comment]
Yes! Closing
