### ISSUE TITLE
way to remap ?

### ISSUE THREAD

**Issue by ArbitRandomUser** [michaeljsmith/vim-indent-object#31]
i would prefer to interchange what vaI and vai. 
for example in julia which has `end` statements and the standard acceptable formatting is 
```
function something (...)
   code
   more code
   even more code
end
```
`vai` is quicker than `vaI` 
i would like to use the quicker `vai` to select the `end` along with the indented block

**Comment by michaeljsmith** [comment]
Hi, thanks for the feedback. The current bindings are chosen to maintain consistency with the existing text objects (word, sentence, etc). Breaking that consistency would make it harder for people to learn to use and remember the keybindings.

However it should be straightforward for you to rebind the keys locally using `:noremap` etc?

**Comment by ArbitRandomUser** [comment]
now that i think about it , indeed consistency would be better.

however just curious how would one go about noremaping to interchange two  plugin keybindings ?

```
vnoremap ai aI
vnoremap aI ai
```
this wouldn't work.
